// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:rick_and_morty/data/models/character/character.dart';
import 'package:rick_and_morty/data/models/character_location/character_location.dart';
import 'package:rick_and_morty/data/models/character_origin/character_origin.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterAdapter());
    registerAdapter(CharacterLocationAdapter());
    registerAdapter(CharacterOriginAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterAdapter());
    registerAdapter(CharacterLocationAdapter());
    registerAdapter(CharacterOriginAdapter());
  }
}
